iLibrary/config/routes.rb
Rails.application.routes.draw do
  resources :bags

  resources :articles

  resources :magazines

  resources :books

  resources :authors

  get 'home/index'

  devise_for :students do get '/users/sign_out' => 'devise/sessions#destroy' end

  root 'home#index'

end

iLibrary/app/models/magazine.rb
class Magazine < ActiveRecord::Base
	has_many :authors

	validates :code, presence: true, uniqueness: true
	validates :title, presence: true

	def self.search(query)
	  if query
	    where("title like ? OR themes like ?", "%#{query}%", "%#{query}%") 
	  else
	    find(:all)
	  end
	end
	
	def authores
		authores.join(',')
	end



end

iLibrary/app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end


  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_magazine
      @magazine = Magazine.find(params[:id])
    end


    def magazine_params
      params.require(:magazine).permit(:code, :title, :review, :num_page, :source, :themes)
    end
end

iLibrary/app/helpers/magazines_helper.rb
module MagazinesHelper
end

iLibrary/app/views/magazines/_form.html.erb
<%= form_for(@magazine) do |f| %>
  <% if @magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% @magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="field">
    <%= f.label :num_page %><br>
    <%= f.number_field :num_page %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :themes %><br>
    <%= f.text_area :themes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

iLibrary/app/views/magazines/edit.html.erb
<h1>Editing magazine</h1>

<%= render 'form' %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

iLibrary/app/views/magazines/index.html.erb
<h1>Listing magazines</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Review</th>
      <th>Num page</th>
      <th>Source</th>
      <th>Themes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.code %></td>
        <td><%= magazine.title %></td>
        <td><%= magazine.review %></td>
        <td><%= magazine.num_page %></td>
        <td><%= magazine.source %></td>
        <td><%= magazine.themes %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine', new_magazine_path %>

iLibrary/app/views/magazines/new.html.erb
<h1>New magazine</h1>

<%= render 'form' %>

<%= link_to 'Back', magazines_path %>

iLibrary/app/views/magazines/show.html.erb
<blockquote>
<h5>
  <strong>Code:</strong>
  <%= @magazine.code %>
</h5>

<h5>
  <strong>Title:</strong>
  <%= @magazine.title %>
</h5>

<h5>
  <strong>Review:</strong>
  <%= @magazine.review %>
</h5>

<h5>
  <strong>Num page:</strong>
  <%= @magazine.num_page %>
</h5>

<h5>
  <strong>Source:</strong>
  <%= @magazine.source %>
</h5>

<h5>
  <strong>Themes:</strong>
  <%= @magazine.themes %>
</h5>
</blockquote>

<%= link_to 'Back', home_index_path %>