iLibrary/config/routes.rb
Rails.application.routes.draw do
  resources :bags

  resources :articles

  resources :magazines

  resources :books

  resources :authors

  get 'home/index'

  devise_for :students do get '/users/sign_out' => 'devise/sessions#destroy' end

  root 'home#index'

end

iLibrary/app/models/book.rb
class Book < ActiveRecord::Base
	has_many :authors


	#attr_accessible :title, :review, :code, :themes, :source, :book_type

	validates :code, presence: true, uniqueness: true
	validates :title, presence: true
	validates :book_type, presence: true



	def self.search(query)
	  if query
	    where("title like ? OR themes like ?", "%#{query}%", "%#{query}%") 
	  else
	    find(:all)
	  end
	end
	


	def authores
			authores.join(',')
	end


end

iLibrary/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:code, :title, :review, :num_page, :book_type, :source, :themes)
    end
end

iLibrary/app/helpers/books_helper.rb
module BooksHelper
end

iLibrary/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="field">
    <%= f.label :num_page %><br>
    <%= f.number_field :num_page %>
  </div>
  <div class="field">
    <%= f.label :book_type %><br>
    <%= f.text_field :book_type %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :themes %><br>
    <%= f.text_area :themes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

iLibrary/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

iLibrary/app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Review</th>
      <th>Num page</th>
      <th>Book type</th>
      <th>Source</th>
      <th>Themes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.code %></td>
        <td><%= book.title %></td>
        <td><%= book.review %></td>
        <td><%= book.num_page %></td>
        <td><%= book.book_type %></td>
        <td><%= book.source %></td>
        <td><%= book.themes %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

iLibrary/app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

iLibrary/app/views/books/show.html.erb
<blockquote>
<h5>
  <strong>Code:</strong>
  <%= @book.code %>
</h5>

<h5>
  <strong>Title:</strong>
  <%= @book.title %>
</h5>

<h5>
  <strong>Review:</strong>
  <%= @book.review %>
</h5>

<h5>
  <strong>Num page:</strong>
  <%= @book.num_page %>
</h5>

<h5>
  <strong>Book type:</strong>
  <%= @book.book_type %>
</h5>

<h5>
  <strong>Source:</strong>
  <%= @book.source %>
</h5>

<h5>
  <strong>Themes:</strong>
  <%= @book.themes %>
</h5>
</blockquote>
<%= link_to 'Back', home_index_path %>